name: Update README with Date

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main  # or your default branch

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update README
        run: |
          python -c "
          import datetime
          import re

          with open('README.md', 'r') as file:
              content = file.read()

          today = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')

          # More flexible regex to match variations in formatting
          pattern = r'(<details>\s*<summary>Last updated</summary>\s*Last updated:).*?(\s*</details>)'
          replacement = r'\1 ' + today + r'\2'

          new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)

          with open('README.md', 'w') as file:
              file.write(new_content)
          "

      - name: Commit and push if changed
        run: |
          git config --global user.email "alexandre.lebeau.1@ens.etsmtl.ca"
          git config --global user.name "Lebeau-Alexandre"

          git add README.md
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update README with current date"
            git push
          fi
