name: Update README with Date

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/60 * * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main  # or your default branch

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update README
        run: |
          python -c "
          import datetime
          import re

          with open('.github/workflows/update-readme.yml', 'r') as file:
              content = file.read()

          

          # More flexible regex to match variations in formatting
          pattern = r'- cron: \'.*\')'
          replacement = r'\1\'{{ range(0, 60) | random }} {{ range(0, 24) | random }} * * *\''

          new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)

          with open('.github/workflows/update-readme.yml', 'w') as file:
              file.write(new_content)
          "

      - name: Commit and push if changed
        run: |
          git config --global user.email "alexandre.lebeau.1@ens.etsmtl.ca"
          git config --global user.name "Lebeau-Alexandre"

          git add .github/workflows/update-readme.yml
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update README with current date"
            git push
          fi
